apiVersion: v1
kind: Service
metadata:
  name: exoforge-nodes
  namespace: exoforge
  labels:
    app.kubernetes.io/name: exoforge-nodes
    app.kubernetes.io/part-of: exoforge
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: exoforge-backend
  ports:
    - name: epmd
      port: 4369
      targetPort: 4369
      protocol: TCP
